[2018-06-01 16:01:11,582] [INFO  ]  [app       :55]  [140736670852032] <class 'PyScraper.server.models.database.Database'>
[2018-06-01 16:01:11,583] [INFO  ]  [app       :56]  [140736670852032] <class 'PyScraper.server.models.project.Project'>
[2018-06-01 16:01:11,623] [INFO  ]  [app       :58]  [140736670852032] Create all tables!
[2018-06-01 16:01:11,632] [INFO  ]  [log       :146]  [123145308692480] Scrapy 1.5.0 started (bot: scrapybot)
[2018-06-01 16:01:11,668] [INFO  ]  [_internal :88]  [140736670852032]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2018-06-01 16:01:11,670] [INFO  ]  [log       :149]  [123145308692480] Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.4.0, Python 3.6.2 (default, Jul 17 2017, 16:44:45) - [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Darwin-16.7.0-x86_64-i386-64bit
[2018-06-01 16:04:57,130] [INFO  ]  [_internal :88]  [123145313947648] 127.0.0.1 - - [01/Jun/2018 16:04:57] "OPTIONS /databases HTTP/1.1" 200 -
[2018-06-01 16:05:58,015] [INFO  ]  [_internal :88]  [123145313947648] 127.0.0.1 - - [01/Jun/2018 16:05:58] "OPTIONS /databases HTTP/1.1" 200 -
[2018-06-01 16:09:59,504] [INFO  ]  [_internal :88]  [123145313947648] 127.0.0.1 - - [01/Jun/2018 16:09:59] "OPTIONS /databases HTTP/1.1" 200 -
[2018-06-01 16:18:08,847] [INFO  ]  [_internal :88]  [123145313947648] 127.0.0.1 - - [01/Jun/2018 16:18:08] "OPTIONS /databases HTTP/1.1" 200 -
[2018-06-01 16:28:04,839] [INFO  ]  [_internal :88]  [123145313947648] 127.0.0.1 - - [01/Jun/2018 16:28:04] "OPTIONS /databases HTTP/1.1" 200 -
[2018-06-01 16:35:39,019] [INFO  ]  [_internal :88]  [123145313947648] 127.0.0.1 - - [01/Jun/2018 16:35:39] "OPTIONS /databases HTTP/1.1" 200 -
[2018-06-01 16:37:52,542] [INFO  ]  [_internal :88]  [123145313947648] 127.0.0.1 - - [01/Jun/2018 16:37:52] "OPTIONS /databases HTTP/1.1" 200 -
[2018-06-01 17:06:01,079] [INFO  ]  [_internal :88]  [123145313947648] 127.0.0.1 - - [01/Jun/2018 17:06:01] "OPTIONS /databases HTTP/1.1" 200 -
[2018-06-01 17:17:31,834] [INFO  ]  [app       :55]  [140736670852032] <class 'PyScraper.server.models.database.Database'>
[2018-06-01 17:17:31,834] [INFO  ]  [app       :56]  [140736670852032] <class 'PyScraper.server.models.project.Project'>
[2018-06-01 17:17:31,868] [INFO  ]  [app       :58]  [140736670852032] Create all tables!
[2018-06-01 17:17:31,876] [INFO  ]  [log       :146]  [123145495642112] Scrapy 1.5.0 started (bot: scrapybot)
[2018-06-01 17:17:31,906] [INFO  ]  [log       :149]  [123145495642112] Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.4.0, Python 3.6.2 (default, Jul 17 2017, 16:44:45) - [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Darwin-16.7.0-x86_64-i386-64bit
[2018-06-01 17:17:31,913] [INFO  ]  [_internal :88]  [140736670852032]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2018-06-01 17:17:33,947] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 17:17:33] "GET / HTTP/1.1" 404 -
[2018-06-01 17:17:34,475] [INFO  ]  [_internal :88]  [123145506152448] 127.0.0.1 - - [01/Jun/2018 17:17:34] "GET /favicon.ico HTTP/1.1" 404 -
[2018-06-01 17:17:39,354] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 17:17:39] "GET /healthz HTTP/1.1" 200 -
[2018-06-01 17:19:55,297] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 17:19:55] "OPTIONS /healthz HTTP/1.1" 200 -
[2018-06-01 17:28:38,638] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 17:28:38] "OPTIONS /healthz HTTP/1.1" 200 -
[2018-06-01 17:37:24,366] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 17:37:24] "OPTIONS /healthz HTTP/1.1" 200 -
[2018-06-01 17:38:20,229] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 17:38:20] "OPTIONS /healthz HTTP/1.1" 200 -
[2018-06-01 17:38:28,621] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 17:38:28] "OPTIONS /healthz HTTP/1.1" 200 -
[2018-06-01 17:39:49,390] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 17:39:49] "OPTIONS /healthz HTTP/1.1" 200 -
[2018-06-01 17:50:32,743] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 17:50:32] "OPTIONS /healthz HTTP/1.1" 200 -
[2018-06-01 17:50:41,043] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 17:50:41] "OPTIONS /healthz HTTP/1.1" 200 -
[2018-06-01 19:44:00,387] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 19:44:00] "GET /1367a9a694dcda8be40c.hot-update.json HTTP/1.1" 404 -
[2018-06-01 19:44:03,574] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 19:44:03] "GET /healthz HTTP/1.1" 200 -
[2018-06-01 19:44:08,182] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 19:44:08] "GET /healthz HTTP/1.1" 200 -
[2018-06-01 19:47:14,201] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 19:47:14] "OPTIONS /databases HTTP/1.1" 200 -
[2018-06-01 19:47:58,801] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 19:47:58] "PUT /databases HTTP/1.1" 400 -
[2018-06-01 19:51:11,012] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 19:51:11] "PUT /databases HTTP/1.1" 400 -
[2018-06-01 19:51:21,984] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 19:51:21] "PUT /databases HTTP/1.1" 400 -
[2018-06-01 19:51:34,513] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 19:51:34] "PUT /databases HTTP/1.1" 400 -
[2018-06-01 20:22:09,203] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ValueError' is not JSON serializable
[2018-06-01 20:22:09,203] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ValueError' is not JSON serializable
[2018-06-01 20:22:09,235] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 20:22:09] "PUT /databases HTTP/1.1" 500 -
[2018-06-01 20:22:59,316] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ValueError' is not JSON serializable
[2018-06-01 20:22:59,316] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ValueError' is not JSON serializable
[2018-06-01 20:22:59,326] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 20:22:59] "PUT /databases HTTP/1.1" 500 -
[2018-06-01 20:24:28,839] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 20:24:28] "PUT /databases HTTP/1.1" 400 -
[2018-06-01 20:24:38,794] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 20:24:38] "PUT /databases HTTP/1.1" 400 -
[2018-06-01 20:25:00,222] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 20:25:00] "PUT /databases HTTP/1.1" 400 -
[2018-06-01 20:26:29,509] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ValueError' is not JSON serializable
[2018-06-01 20:26:29,509] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ValueError' is not JSON serializable
[2018-06-01 20:26:29,518] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 20:26:29] "PUT /databases HTTP/1.1" 500 -
[2018-06-01 20:27:03,818] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ValueError' is not JSON serializable
[2018-06-01 20:27:03,818] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ValueError' is not JSON serializable
[2018-06-01 20:27:03,822] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 20:27:03] "PUT /databases HTTP/1.1" 500 -
[2018-06-01 20:27:38,394] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ValueError' is not JSON serializable
[2018-06-01 20:27:38,394] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ValueError' is not JSON serializable
[2018-06-01 20:27:38,404] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 20:27:38] "PUT /databases HTTP/1.1" 500 -
[2018-06-01 20:29:12,586] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 20:29:12] "PUT /databases HTTP/1.1" 400 -
[2018-06-01 20:29:59,080] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'InternalError' is not JSON serializable
[2018-06-01 20:29:59,080] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'InternalError' is not JSON serializable
[2018-06-01 20:29:59,083] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 20:29:59] "PUT /databases HTTP/1.1" 500 -
[2018-06-01 20:41:56,233] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'InternalError' is not JSON serializable
[2018-06-01 20:41:56,233] [ERROR ]  [app       :1761]  [123145500897280] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'InternalError' is not JSON serializable
[2018-06-01 20:41:56,251] [INFO  ]  [_internal :88]  [123145500897280] 127.0.0.1 - - [01/Jun/2018 20:41:56] "PUT /databases HTTP/1.1" 500 -
[2018-06-01 20:42:34,053] [INFO  ]  [app       :55]  [140736670852032] <class 'PyScraper.server.models.database.Database'>
[2018-06-01 20:42:34,053] [INFO  ]  [app       :56]  [140736670852032] <class 'PyScraper.server.models.project.Project'>
[2018-06-01 20:42:34,104] [INFO  ]  [app       :58]  [140736670852032] Create all tables!
[2018-06-01 20:42:34,114] [INFO  ]  [log       :146]  [123145557823488] Scrapy 1.5.0 started (bot: scrapybot)
[2018-06-01 20:42:34,180] [INFO  ]  [log       :149]  [123145557823488] Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.4.0, Python 3.6.2 (default, Jul 17 2017, 16:44:45) - [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Darwin-16.7.0-x86_64-i386-64bit
[2018-06-01 20:42:34,227] [INFO  ]  [_internal :88]  [140736670852032]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2018-06-01 20:42:35,835] [ERROR ]  [app       :1761]  [123145563078656] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'InternalError' is not JSON serializable
[2018-06-01 20:42:35,835] [ERROR ]  [app       :1761]  [123145563078656] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'InternalError' is not JSON serializable
[2018-06-01 20:42:35,859] [INFO  ]  [_internal :88]  [123145563078656] 127.0.0.1 - - [01/Jun/2018 20:42:35] "PUT /databases HTTP/1.1" 500 -
[2018-06-01 20:43:33,638] [INFO  ]  [app       :55]  [140736670852032] <class 'PyScraper.server.models.database.Database'>
[2018-06-01 20:43:33,639] [INFO  ]  [app       :56]  [140736670852032] <class 'PyScraper.server.models.project.Project'>
[2018-06-01 20:43:33,666] [INFO  ]  [app       :58]  [140736670852032] Create all tables!
[2018-06-01 20:43:33,673] [INFO  ]  [log       :146]  [123145417273344] Scrapy 1.5.0 started (bot: scrapybot)
[2018-06-01 20:43:33,704] [INFO  ]  [log       :149]  [123145417273344] Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.4.0, Python 3.6.2 (default, Jul 17 2017, 16:44:45) - [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Darwin-16.7.0-x86_64-i386-64bit
[2018-06-01 20:43:33,705] [INFO  ]  [_internal :88]  [140736670852032]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2018-06-01 20:43:36,353] [INFO  ]  [_internal :88]  [123145422528512] 127.0.0.1 - - [01/Jun/2018 20:43:36] "PUT /databases HTTP/1.1" 400 -
[2018-06-01 20:43:52,384] [INFO  ]  [_internal :88]  [123145422528512] 127.0.0.1 - - [01/Jun/2018 20:43:52] "PUT /databases HTTP/1.1" 400 -
[2018-06-01 20:44:23,408] [ERROR ]  [app       :1761]  [123145422528512] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'InternalError' is not JSON serializable
[2018-06-01 20:44:23,408] [ERROR ]  [app       :1761]  [123145422528512] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'InternalError' is not JSON serializable
[2018-06-01 20:44:23,417] [INFO  ]  [_internal :88]  [123145422528512] 127.0.0.1 - - [01/Jun/2018 20:44:23] "PUT /databases HTTP/1.1" 500 -
[2018-06-01 21:23:37,612] [ERROR ]  [app       :1761]  [123145422528512] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'KeyError' is not JSON serializable
[2018-06-01 21:23:37,612] [ERROR ]  [app       :1761]  [123145422528512] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'KeyError' is not JSON serializable
[2018-06-01 21:23:37,627] [INFO  ]  [_internal :88]  [123145422528512] 127.0.0.1 - - [01/Jun/2018 21:23:37] "PUT /databases HTTP/1.1" 500 -
[2018-06-01 21:23:59,897] [INFO  ]  [_internal :88]  [123145422528512] 127.0.0.1 - - [01/Jun/2018 21:23:59] "PUT /databases HTTP/1.1" 400 -
[2018-06-01 21:24:06,036] [ERROR ]  [app       :1761]  [123145422528512] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'KeyError' is not JSON serializable
[2018-06-01 21:24:06,036] [ERROR ]  [app       :1761]  [123145422528512] Exception on /databases [PUT]
Traceback (most recent call last):
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/nikan/Eigen/python_envs/PyScraper/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'KeyError' is not JSON serializable
[2018-06-01 21:24:06,041] [INFO  ]  [_internal :88]  [123145422528512] 127.0.0.1 - - [01/Jun/2018 21:24:06] "PUT /databases HTTP/1.1" 500 -
[2018-06-01 21:29:29,349] [INFO  ]  [app       :55]  [140736670852032] <class 'PyScraper.server.models.database.Database'>
[2018-06-01 21:29:29,350] [INFO  ]  [app       :56]  [140736670852032] <class 'PyScraper.server.models.project.Project'>
[2018-06-01 21:29:29,372] [INFO  ]  [app       :58]  [140736670852032] Create all tables!
[2018-06-01 21:29:29,386] [INFO  ]  [log       :146]  [123145378492416] Scrapy 1.5.0 started (bot: scrapybot)
[2018-06-01 21:29:29,418] [INFO  ]  [_internal :88]  [140736670852032]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2018-06-01 21:29:29,429] [INFO  ]  [log       :149]  [123145378492416] Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.4.0, Python 3.6.2 (default, Jul 17 2017, 16:44:45) - [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Darwin-16.7.0-x86_64-i386-64bit
[2018-06-01 21:29:32,931] [INFO  ]  [_internal :88]  [123145383747584] 127.0.0.1 - - [01/Jun/2018 21:29:32] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:29:37,181] [INFO  ]  [_internal :88]  [123145383747584] 127.0.0.1 - - [01/Jun/2018 21:29:37] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:30:15,920] [INFO  ]  [app       :55]  [140736670852032] <class 'PyScraper.server.models.database.Database'>
[2018-06-01 21:30:15,920] [INFO  ]  [app       :56]  [140736670852032] <class 'PyScraper.server.models.project.Project'>
[2018-06-01 21:30:15,964] [INFO  ]  [app       :58]  [140736670852032] Create all tables!
[2018-06-01 21:30:15,974] [INFO  ]  [log       :146]  [123145368805376] Scrapy 1.5.0 started (bot: scrapybot)
[2018-06-01 21:30:16,014] [INFO  ]  [log       :149]  [123145368805376] Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.4.0, Python 3.6.2 (default, Jul 17 2017, 16:44:45) - [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Darwin-16.7.0-x86_64-i386-64bit
[2018-06-01 21:30:16,015] [INFO  ]  [_internal :88]  [140736670852032]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2018-06-01 21:30:22,638] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:30:22] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:30:26,413] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:30:26] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:30:36,121] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:30:36] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:30:57,388] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:30:57] "PUT /databases HTTP/1.1" 400 -
[2018-06-01 21:33:19,262] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:33:19] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:33:31,436] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:33:31] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:34:07,868] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:34:07] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:43:57,409] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:43:57] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:44:56,949] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:44:56] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:50:07,092] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:50:07] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:50:15,537] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:50:15] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:51:18,524] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:51:18] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:51:26,113] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:51:26] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:52:01,975] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:52:01] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:52:12,376] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:52:12] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 21:54:18,828] [INFO  ]  [_internal :88]  [123145374060544] 127.0.0.1 - - [01/Jun/2018 21:54:18] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 22:15:35,337] [INFO  ]  [app       :55]  [140736670852032] <class 'PyScraper.server.models.database.Database'>
[2018-06-01 22:15:35,338] [INFO  ]  [app       :56]  [140736670852032] <class 'PyScraper.server.models.project.Project'>
[2018-06-01 22:15:35,356] [INFO  ]  [app       :58]  [140736670852032] Create all tables!
[2018-06-01 22:15:35,364] [INFO  ]  [log       :146]  [123145539137536] Scrapy 1.5.0 started (bot: scrapybot)
[2018-06-01 22:15:35,396] [INFO  ]  [log       :149]  [123145539137536] Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.4.0, Python 3.6.2 (default, Jul 17 2017, 16:44:45) - [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Darwin-16.7.0-x86_64-i386-64bit
[2018-06-01 22:15:35,400] [INFO  ]  [_internal :88]  [140736670852032]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2018-06-01 22:15:43,263] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:43] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:44,561] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:44] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:45,212] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:45] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:45,593] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:45] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:45,865] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:45] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:46,129] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:46] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:46,315] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:46] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:46,574] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:46] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:46,822] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:46] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:47,363] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:47] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:48,363] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:48] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:49,237] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:49] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:49,757] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:49] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:50,093] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:50] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:50,341] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:50] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:50,587] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:50] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:50,878] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:50] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:51,085] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:51] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:51,767] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:51] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 22:15:52,953] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 22:15:52] "PUT /databases HTTP/1.1" 403 -
[2018-06-01 23:03:54,390] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:03:54] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 23:17:11,172] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:17:11] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:18:01,384] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:18:01] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:19:23,292] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:19:23] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:19:51,020] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:19:51] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:20:01,781] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:20:01] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:20:38,924] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:20:38] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:20:40,504] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:20:40] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:21:38,730] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:21:38] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:21:40,523] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:21:40] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:21:51,797] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:21:51] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:21:53,436] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:21:53] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:46:27,834] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:46:27] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:48:45,986] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:48:45] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:52:12,903] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:52:12] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:52:26,961] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:52:26] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:54:03,689] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:54:03] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:57:04,838] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:57:04] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:57:22,346] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:57:22] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 23:57:22,383] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:57:22] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:58:52,007] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:58:52] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:59:07,983] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:59:07] "PUT /databases HTTP/1.1" 200 -
[2018-06-01 23:59:08,031] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:59:08] "GET /databases HTTP/1.1" 200 -
[2018-06-01 23:59:35,174] [INFO  ]  [_internal :88]  [123145544392704] 127.0.0.1 - - [01/Jun/2018 23:59:35] "GET /databases HTTP/1.1" 200 -
